[2023-02-12 02:09:09,164] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados manual__2023-02-12T05:09:00.538571+00:00 [queued]>
[2023-02-12 02:09:09,172] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados manual__2023-02-12T05:09:00.538571+00:00 [queued]>
[2023-02-12 02:09:09,172] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-12 02:09:09,172] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-12 02:09:09,173] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-12 02:09:09,188] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-02-12 05:09:00.538571+00:00
[2023-02-12 02:09:09,191] {standard_task_runner.py:52} INFO - Started process 23795 to run task
[2023-02-12 02:09:09,200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'manual__2023-02-12T05:09:00.538571+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/tf/5c5cm4z11mvb4z72rkp1jvxw0000gn/T/tmpkp66e9e1', '--error-file', '/var/folders/tf/5c5cm4z11mvb4z72rkp1jvxw0000gn/T/tmpayvg46jj']
[2023-02-12 02:09:09,203] {standard_task_runner.py:80} INFO - Job 14: Subtask extrai_dados
[2023-02-12 02:09:09,271] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados manual__2023-02-12T05:09:00.538571+00:00 [running]> on host Mac-Mikeias.local
[2023-02-12 02:09:09,338] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-02-12T05:09:00.538571+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-12T05:09:00.538571+00:00
[2023-02-12 02:09:10,285] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGABRT
[2023-02-12 02:09:10,303] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230212T050900, start_date=20230212T050909, end_date=20230212T050910
[2023-02-12 02:09:10,366] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
